name: Build and Push Frontend Image

on:
  push:
    branches:
      - main
    #if changes are made to the backend folder, only then do we rebuild the docker image
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/captain-coc0/pixelparty-frontend:latest